### ISSUE TITLE
python: blank lines in classes

### ISSUE THREAD

**Issue by geratheon** [metakirby5/codi.vim#18] opened 2016-08-16 14:43 UTC
When you define a class in python and use empty lines between functions, everything breaks.

![2016-08-16-164152_655x412_scrot](https://cloud.githubusercontent.com/assets/5645703/17702987/61b67a9c-63d0-11e6-86ab-14f4999464e7.png)

But when you remove those lines, everything is good.

![2016-08-16-164159_655x412_scrot](https://cloud.githubusercontent.com/assets/5645703/17702993/6a8fe25c-63d0-11e6-977a-15a612bf12db.png)

I'm not really sure if this is a problem with codi.vim or with python, but the script itself is legit python code, even with the blank line.

**Comment by balta2ar** [comment] 2016-08-16 15:21
This might be due to how pasting is implemented. That empty line before `do_stuff` is considered to be the end-of-paste. IIRC, ipython has %paste and %cpaste to avoid this.

**Comment by metakirby5** [comment] 2016-08-16 18:02
@balta2ar is correct. If you use the standard Python interpreter, it won't let you define a class like that either. Codi is more or less a wrapper around the interpreter, so this is expected behavior that won't be fixed. I will, however, add a note about this to the docs - thanks for the find!

**Closed by metakirby5** 2016-08-16 18:02 UTC
