### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by sygi** [metakirby5/codi.vim#70] opened 2017-07-12 10:14 UTC
I am having problems installing codi (with pathogen). After installation, it doesn't seem to work (opens only the second split, but doesn't print there anything, despite using `:CodiUpdate`). I also don't see anything in `codi-introduction-gotchas`.
Do you have an idea what could have gone wrong?

## Issue description
- A minimal `.vimrc` that will reproduce the issue:
```
execute pathogen#infect()
```
- Exact steps to reproduce the issue, starting with the command used to open
  `vim`:
```
vim a.py
:Codi python
```
- asciinema:
[![asciicast](https://asciinema.org/a/b4bPJBqZJsxQRMRkbGrVzMoxc.png)](https://asciinema.org/a/b4bPJBqZJsxQRMRkbGrVzMoxc)

## Environment
- Operating system: Lubuntu 14.04,
```
$ uname -a                            
Linux thinkpad 3.13.0-123-generic #172-Ubuntu SMP Mon Jun 26 18:04:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Version of `script`:
```
$ script --version
script from util-linux 2.20.1
```
- Entire output of vim --version:
https://gist.github.com/sygi/53ac64cdd4ec41f73ab8ed9eb90a648c
- Log lines (see `:h g:codi#log`)
```
$ cat ~/codi.log 
[10:35:18.104803] <SNR>41_user_au: Doing autocommand CodiLeavePost
```

**Comment by meeuw** [comment] 2017-09-23 18:45
I've just discovered that `/tmp/cmd` isn't created with execute permissions, using `chmod 700 /tmp/cmd` did the trick for me.

**Comment by metakirby5** [comment] 2017-10-01 17:50
@meeuw, thanks for looking into this. I've added a `setfperm` call at 93cfc91. @sygi, please check out the `cmd-perm` branch and see if it fixes the issue. I can't test Linux at the moment, but I would like to confirm that it works before merging it.

**Comment by metakirby5** [comment] 2017-10-01 17:54
Also, since this seems to be a duplicate of #62, let's redirect discussion there.

**Closed by metakirby5** 2017-10-01 17:54 UTC

**Comment by sygi** [comment] 2017-10-03 12:53
Thanks for looking into that. I tried cmd-perm branch and it changed something, but didn't fully help.

I now see the correct output in log (see later), but still the other buffer doesn't get updated. I don't think it is a duplicate of  #62, as there even the interpreter didn't start and wasn't calculating the expressions.
```
[13:49:02.223903] <SNR>29_codi_do_update[29]: Starting job for buffer 1
[13:49:02.225409] <SNR>29_codi_do_update[65]: [INPUT] a = 13aa + 1"a"

[13:49:02.225613] <SNR>29_codi_do_update[66]: Expecting 6 prompts
[13:49:02.226150] <SNR>29_user_au[1]: Doing autocommand CodiEnterPost
[13:49:02.244006] <SNR>29_codi_handle_data[9]: [DATA] Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[13:49:02.244271] <SNR>29_codi_handle_data[9]: [DATA] [GCC 4.8.4] on linux2
[13:49:02.244548] <SNR>29_codi_handle_data[9]: [DATA] Type "help", "copyright", "credits" or "license" for more information.
[13:49:02.244768] <SNR>29_codi_handle_data[9]: [DATA] >>> >>> 13
[13:49:02.244862] <SNR>29_codi_handle_data[14]: Matched prompt
[13:49:02.245079] <SNR>29_codi_handle_data[9]: [DATA] >>> 14
[13:49:02.245172] <SNR>29_codi_handle_data[14]: Matched prompt
[13:49:02.245360] <SNR>29_codi_handle_data[9]: [DATA] >>> >>> 'a'
[13:49:02.245449] <SNR>29_codi_handle_data[14]: Matched prompt
[13:49:02.245632] <SNR>29_codi_handle_data[9]: [DATA] >>> >>> 
[13:49:02.245720] <SNR>29_codi_handle_data[14]: Matched prompt
[13:49:07.403523] <SNR>29_user_au[1]: Doing autocommand CodiUpdatePre
[13:49:07.405544] <SNR>29_codi_do_update[29]: Starting job for buffer 1
[13:49:07.409054] <SNR>29_stop_job_for_buf[8]: Stopping job for buffer 1
[13:49:07.409895] <SNR>29_codi_do_update[65]: [INPUT] a = 13aa + 1"a"

[13:49:07.410505] <SNR>29_codi_do_update[66]: Expecting 6 prompts
[13:49:07.459004] <SNR>29_codi_handle_data[9]: [DATA] Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[13:49:07.459688] <SNR>29_codi_handle_data[9]: [DATA] [GCC 4.8.4] on linux2
[13:49:07.460230] <SNR>29_codi_handle_data[9]: [DATA] Type "help", "copyright", "credits" or "license" for more information.
[13:49:07.460723] <SNR>29_codi_handle_data[9]: [DATA] >>> >>> 13
[13:49:07.460943] <SNR>29_codi_handle_data[14]: Matched prompt
[13:49:07.461443] <SNR>29_codi_handle_data[9]: [DATA] >>> 14
[13:49:07.461660] <SNR>29_codi_handle_data[14]: Matched prompt
[13:49:07.462138] <SNR>29_codi_handle_data[9]: [DATA] >>> >>> 'a'
[13:49:07.462355] <SNR>29_codi_handle_data[14]: Matched prompt
[13:49:07.462838] <SNR>29_codi_handle_data[9]: [DATA] >>> >>> 
[13:49:07.463036] <SNR>29_codi_handle_data[14]: Matched prompt
[13:49:08.421569] <SNR>29_user_au[1]: Doing autocommand CodiLeavePre
[13:49:08.423799] <SNR>29_user_au[1]: Doing autocommand CodiLeavePost
```
